### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [4]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 2 - torch.unsqueeze() / torch.squeeze()

In [104]:
# Example 1
a = torch.randint(5, size=(3,1,2))
print(a.shape)
print(a)
print("-" * 25)
b = torch.unsqueeze(a, dim=-1)
print(b.shape)
print(b)

torch.Size([3, 1, 2])
tensor([[[4, 0]],

        [[3, 4]],

        [[1, 3]]])
-------------------------
torch.Size([3, 1, 2, 1])
tensor([[[[4],
          [0]]],


        [[[3],
          [4]]],


        [[[1],
          [3]]]])


In [105]:
# Example 2
c = torch.squeeze(a)
print(c.shape)
print(c)

torch.Size([3, 2])
tensor([[4, 0],
        [3, 4],
        [1, 3]])


### Function 3 - torch.unsqueeze() / torch.squeeze()

In [106]:
# Example 1
a = torch.randn((3, 2, 4))
print(a.shape)
print(a)
print("-" * 55)
b = a.transpose(0,1)
print(b.shape)
print(b)

torch.Size([3, 2, 4])
tensor([[[-0.4046, -0.5239,  0.0899, -1.0204],
         [-0.1899, -1.8733,  0.8128, -0.8176]],

        [[ 1.2240, -1.0576,  0.0716,  0.0999],
         [-0.5310,  1.2386,  0.2477,  1.2607]],

        [[ 0.6974, -0.2596,  2.1029,  0.1638],
         [-0.9287, -1.1170,  0.5979,  1.5543]]])
-------------------------------------------------------
torch.Size([2, 3, 4])
tensor([[[-0.4046, -0.5239,  0.0899, -1.0204],
         [ 1.2240, -1.0576,  0.0716,  0.0999],
         [ 0.6974, -0.2596,  2.1029,  0.1638]],

        [[-0.1899, -1.8733,  0.8128, -0.8176],
         [-0.5310,  1.2386,  0.2477,  1.2607],
         [-0.9287, -1.1170,  0.5979,  1.5543]]])


In [107]:
# Example 2
c = a.permute(2,0,1)
print(c.shape)
print(c)

torch.Size([4, 3, 2])
tensor([[[-0.4046, -0.1899],
         [ 1.2240, -0.5310],
         [ 0.6974, -0.9287]],

        [[-0.5239, -1.8733],
         [-1.0576,  1.2386],
         [-0.2596, -1.1170]],

        [[ 0.0899,  0.8128],
         [ 0.0716,  0.2477],
         [ 2.1029,  0.5979]],

        [[-1.0204, -0.8176],
         [ 0.0999,  1.2607],
         [ 0.1638,  1.5543]]])


### Function 4 - tensor.reshape() / tensor.view()

In [109]:
# Example 1
a = torch.randint(10, size=(2, 3, 4))
print(a.shape)
print(a)
print("-" * 25)
b = a.reshape((2,3,2,2))
print(b.shape)
print(b)

torch.Size([2, 3, 4])
tensor([[[0, 1, 4, 8],
         [5, 5, 9, 6],
         [4, 9, 6, 4]],

        [[5, 7, 8, 8],
         [8, 8, 8, 6],
         [1, 9, 8, 9]]])
-------------------------
torch.Size([2, 3, 2, 2])
tensor([[[[0, 1],
          [4, 8]],

         [[5, 5],
          [9, 6]],

         [[4, 9],
          [6, 4]]],


        [[[5, 7],
          [8, 8]],

         [[8, 8],
          [8, 6]],

         [[1, 9],
          [8, 9]]]])


In [110]:
# Example 2
c = a.view((2,-1))
print(c.shape)
print(c)

torch.Size([2, 12])
tensor([[0, 1, 4, 8, 5, 5, 9, 6, 4, 9, 6, 4],
        [5, 7, 8, 8, 8, 8, 8, 6, 1, 9, 8, 9]])
